### ISSUE TITLE
ELIXIR-wide metrics

### ISSUE THREAD

**Issue by mihai-sysbio** [elixir-europe-training/ELIXIR-TrP-Training-Metrics-Database-Tango#2]
**User story**
As an impact officer, I want to see up-to-date dashboard across all nodes, so that I can use these when creating impact stories.

**Sub-stories**
- [ ] I can navigate to Tango without login.
- [ ] I can see ELIXIR-wide metrics (same visualisations as for Node-specific data).
- [ ] I can download the data used to create the charts (aggregated metrics) in CSV/Excel format.
- [ ] I can export any chart in a graphical format (JPEG/PNG/SVG etc).

**Comment by mihai-sysbio** [comment]
Before closing this issue:
- [ ] check that the TMD and Tango metrics match
- [ ] ask Erika if there are other charts she would want, and create new issues for those

**Comment by ninanorgren** [comment]
Metrics from old and new TMD do not match. Need to figure out why. Data was exported from old TMD to csv, and from there imported into new TMD.

**Comment by brane007** [comment]
Metrics between imported csv files and metrics shown on new TMD do match, so there was no error with data import. There might be an issue with data export from old TMD or metrics that is being shown on old TMD.

**Comment by brane007** [comment]
The difference exists because some metrics data from UK node was imported into old TMD after the export of data to new TMD. When bulk upload of new TMD will be operational, UK node will have to import these data also to new TMD. Otherwise metrics between old and new TMDs match.
