### ISSUE TITLE
bulk upload

### ISSUE THREAD

**Issue by mihai-sysbio** [elixir-europe-training/ELIXIR-TrP-Training-Metrics-Database-Tango#3]
**User story**
As a Training coordinator, I want to upload metrics for a given course, so that it shows up in the aggregated metrics. These metrics are: Quality metrics, Demographics metrics and Impact metrics.

**Sub-stories**
- [ ] As a user, I can log in with username/email and password.
- [ ] I am recognized as an authorized user (such as Training Coordinator) for my node.
- [ ] I can add a new event for my node manually thought the UI.
- [ ] I can see if there are any issues while adding the event, such as incomplete fields, wrong field formats etc.
- [ ] I can see a confirmation that the event has been added successfully.
- [ ] I can see the course identifier created by Tango for the course I just added.
- [ ] I can upload bulk metrics data individually, for any type, in any order.
- [ ] I am notified of any errors in the data I provide before it is inserted into the database.
- [ ] I see a confirmation that the data has been added successfully.

**Comment by pdmnyberg** [comment]
It might be a good idea to have a look at the current functionality and reevaluate this issue. Or we keep it as is.

**Comment by pdmnyberg** [comment]
Should it really be possible to delete individual rows for metrics types? To me it makes more sense that it is symmetrical with the upload. So bulk upload / bulk delete.

**Comment by pdmnyberg** [comment]
Should the following `Tango will alert me if there are more metrics rows than event participants.` alert be in the form of an error or a warning? Should it still allow the upload of the data?

**Comment by mihai-sysbio** [comment]
> Should the following `Tango will alert me if there are more metrics rows than event participants.` alert be in the form of an error or a warning? Should it still allow the upload of the data?

Unsure if a decision was taken here, I'd propose to alert and stop the upload - one cannot know which rows are "correct" to upload.

**Comment by pdmnyberg** [comment]
I think it might be a good idea to try to move the last points of this issue into separate issues in order to be able to close this one.

For the functionality of bulk upload I think we have a working solution and the remaining points are more in the territory of general data management.
